// Generated by CoffeeScript 1.12.5
module.exports = function(robot) {
  var brainKey, getKakei;
  brainKey = 'kakei';
  robot.hear(/くらす(.*)/i, function(res) {
    var kakei, spendMoney;
    spendMoney = res.match[1];
    kakei = getKakei();
    robot.brain.set(brainKey, spendMoney);
    return res.send("「くらす」に" + spendMoney + "円を使いました。残高は、...\n「くらす」は" + kakei + "です。「\n「食べる」は..です。");
  });
  return getKakei = function() {
    var ref;
    return (ref = robot.brain.get(brainKey)) != null ? ref : [];
  };
};
