// Generated by CoffeeScript 1.12.5
module.exports = function(robot) {
  return robot.hear(/予算/i, function(res) {
    var url;
    url = "https://script.google.com/macros/s/AKfycbyqYYjmdd-TnNz1mzy_c3zOLpHGHKd-jSYuqqXo71m-s_zqxIYH/exec";
    url = url + "?type=badget";
    return robot.http(url).get()(function(err, httpRes, body) {
      if (err) {
        res.send("Encountered an error :( " + err);
        return;
      }
      url = httpRes.headers.location;
      return robot.http(url).get()(function(err, httpRes, body) {
        var data;
        data = JSON.parse(body);
        return res.send("---予算---\n" + data.category[0] + " : " + data.badget[0] + "\n" + data.category[1] + " : " + data.badget[1] + "\n" + data.category[2] + " : " + data.badget[2] + "\n" + data.category[3] + " : " + data.badget[3]);
      });
    });
  });
};
